spring:
  application:
    name: store
server:
  port: 8080
payment:
  gateway: stripe
stripe:
  apiUrl: https://api.stripe.com
  timeout: 5000
  enabled: true
  currencies: USD,EUR,GBP
mail:
  host: https://smtp.gmail.com
  port: 587
