spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://db:3306/codewithmosh-store?createDatabaseIfNotExist=true
    username: mosh
    password: password
server:
  port: 8080
payment:
  gateway: stripe
stripe:
  apiUrl: https://api.stripe.com
  timeout: 5000
  enabled: true
  currencies: USD,EUR,GBP
mail:
  host: https://smtp.gmail.com
  port: 587
