spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://db:3306/codewithmosh-store?createDatabaseIfNotExist=true
    username: mosh
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
server:
  port: 8080
