services:
  dev:
    image: registry.gitlab.com/mu-bd-ce/devcontainers/java:latest
    volumes:
      - ..:/workspaces/workspace
    stdin_open: true
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: codewithmosh-store
      MYSQL_USER: mosh
      MYSQL_PASSWORD: password
    volumes:
      - ./data:/var/lib/mysql